### PR TITLE
Update nan to version 2.0

### PR DESCRIPTION
**Pull request by gisenberg**
This PR updates the nan package dependency from 1.6.1 to 2.0.0. This is the result of running https://gist.github.com/thlorenz/7e9d8ad15566c99fd116 on the relevant source files.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Hey @gisenberg, can you please add Node 4 to the build matrix [here](https://github.com/atom/scrollbar-style/blob/master/.travis.yml#L8)?  Thanks.

/cc @zcbenz

**Comment by gisenberg** [comment]
Working on it, thanks for pointing me in the right direction.

**Comment by 50Wliu** [comment]
I forgot that Travis is super-outdated...adding these two lines should (hopefully) fix the build:
https://github.com/atom/node-runas/blob/master/.travis.yml#L16-L17
(Also, if you feel like it, it wouldn't hurt to add a `sudo: false` line to switch the build onto the new container infrastructure).

**Comment by gisenberg** [comment]
Thanks! Pushed and running through CI now.

**Comment by 50Wliu** [comment]
:green_apple: Thanks a lot @gisenberg!

**Pull request merged**
